# Trains a tiny (9 -> 10 -> 2) neural net that decides how much an NPC's opinion of the player
# should shift, and how likely it is to shove the player, given:
#   curiosity, friendliness, patience   (the NPC's personality)
#   opinion, timesTalked                (the NPC's memory of the player so far)
#   colorMatch, aggression, dayNight    (what the player is wearing / has been doing / time of day)
#   response                            (what the player just said: +1 friendly ... 0 neutral ... -1 rude)
#
# There's no real player-interaction log to learn from (this is a fresh game), so we bootstrap with a
# hand-written "teacher" function that encodes sensible behavior, generate many random examples from it,
# and train the net to approximate that function. This is a completely standard way to start a game AI
# before real play data exists - the net is real and trained, it's just trained on designed priors.
#
# Run this once with Python (pip install numpy scikit-learn), then rebuild the game as normal. Players
# never need Python - only you, if you want to retrain with different personalities or rules.
import numpy as np
from sklearn.neural_network import MLPRegressor

rng = np.random.default_rng(42)
N = 8000

curiosity     = rng.uniform(0, 1, N)
friendliness  = rng.uniform(0, 1, N)
patience      = rng.uniform(0, 1, N)
opinion       = rng.uniform(-100, 100, N)
timesTalked   = rng.uniform(0, 20, N)
colorMatch    = rng.choice([-1, 0, 1], N)      # -1 disliked color, 0 neither, 1 favorite color
aggression    = rng.uniform(0, 1, N)           # 1 = player has been swinging a stick around / acting hostile
dayNight      = rng.uniform(0, 1, N)           # 1 = full day, 0 = full night
response      = rng.choice([-1.0, -0.8, -0.6, -0.4, 0.0, 0.2, 0.5, 0.6, 1.0], N)   # what the player said

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# The teacher function: friendly NPCs care more about your color and enjoy kind answers more, impatient
# NPCs punish hostility and rudeness harder, curious NPCs warm up with repeat visits and with answers
# that share something real (neutral/sad), and existing opinion has some momentum.
delta = (
    2.0
    + friendliness * colorMatch * 6.0
    - aggression * (1.2 - patience) * 5.0
    + curiosity * np.minimum(timesTalked, 5) * 0.3
    + (opinion / 100.0) * 1.5
    + response * (2.0 + friendliness * 3.0)
    - np.maximum(0, -response) * (1.2 - patience) * 3.0
    + (1 - np.abs(response)) * curiosity * 1.0
)
delta = np.clip(delta, -10, 10)
punch = sigmoid(-(opinion + 50) / 15.0 - patience * 3 + aggression * 2 - response * 1.5)

X = np.column_stack([curiosity, friendliness, patience, opinion / 100.0, timesTalked / 20.0,
                     colorMatch, aggression, dayNight, response])
Y = np.column_stack([delta / 10.0, punch])   # keep targets in a small range; the C++ side un-scales opinionDelta by *10

HIDDEN = 10
model = MLPRegressor(hidden_layer_sizes=(HIDDEN,), activation="tanh", max_iter=6000, random_state=0)
model.fit(X, Y)

W1, W2 = model.coefs_
B1, B2 = model.intercepts_

def emit(name, arr):
    if arr.ndim == 1:
        vals = ", ".join(f"{v:.6f}f" for v in arr)
        return f"const float {name}[{len(arr)}] = {{{vals}}};"
    rows = ["{" + ", ".join(f"{v:.6f}f" for v in row) + "}" for row in arr]
    return f"const float {name}[{arr.shape[0]}][{arr.shape[1]}] = {{{', '.join(rows)}}};"

with open("npc_brain_weights.h", "w") as f:
    f.write("// AUTO-GENERATED by train_brain.py - do not edit by hand. Re-run the script to regenerate.\n")
    f.write("#pragma once\n")
    f.write("const int BRAIN_INPUTS = 9;\n")
    f.write(f"const int HIDDEN_SIZE = {HIDDEN};\n")
    f.write(emit("W1", W1) + "\n")
    f.write(emit("B1", B1) + "\n")
    f.write(emit("W2", W2) + "\n")
    f.write(emit("B2", B2) + "\n")

def check(label, row):
    out = model.predict([row])[0] * [10, 1]
    print(f"{label:<62} delta={out[0]:+6.2f}  punch={out[1]:.2f}")

print("Wrote npc_brain_weights.h")
# order: curiosity, friendliness, patience, opinion/100, timesTalked/20, colorMatch, aggression, dayNight, response
check("friendly NPC, favorite color, says nothing", [0.8, 0.9, 0.5, 0, 2/20, 1, 0, 0.5, 0])
check("friendly NPC, neutral opinion, player answers HAPPY", [0.8, 0.9, 0.5, 0, 2/20, 0, 0, 0.5, 1])
check("friendly NPC, neutral opinion, player answers MAD", [0.8, 0.9, 0.5, 0, 2/20, 0, 0, 0.5, -1])
check("impatient NPC, disliked color, hostile player, rude answer", [0.3, 0.3, 0.1, -0.6, 10/20, -1, 1, 0.5, -1])