# Trains a tiny (8 -> 8 -> 2) neural net that decides how much an NPC's opinion
# of the player should shift, and how likely it is to punch the player, given:
#   curiosity, friendliness, patience   (the NPC's personality)
#   opinion, timesTalked                (the NPC's memory of the player so far)
#   colorMatch, aggression, dayNight    (what the player just did)
#
# There's no real player-interaction log to learn from (this is a fresh game),
# so we bootstrap with a hand-written "teacher" function that encodes sensible
# behavior, generate many random examples from it, and train the net to
# approximate that function. This is a completely standard way to start a game
# AI system before real play data exists - the net is real and trained, it's
# just trained on designed priors rather than logged play sessions.
#
# Run this once with Python (pip install numpy scikit-learn), then rebuild the
# game as normal. Players never need Python - only you, if you want to retrain
# with different personalities or rules.
import numpy as np
from sklearn.neural_network import MLPRegressor

rng = np.random.default_rng(42)
N = 4000

curiosity     = rng.uniform(0, 1, N)
friendliness  = rng.uniform(0, 1, N)
patience      = rng.uniform(0, 1, N)
opinion       = rng.uniform(-100, 100, N)
timesTalked   = rng.uniform(0, 20, N)
colorMatch    = rng.choice([-1, 0, 1], N)     # -1 disliked color, 0 neither, 1 favorite color
aggression    = rng.uniform(0, 1, N)          # 1 = player has been damaging flowers / acting hostile
dayNight      = rng.uniform(0, 1, N)          # 1 = full day, 0 = full night

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# The teacher function: friendly NPCs care more about your color choice,
# impatient NPCs punish hostility harder, curious NPCs warm up faster with
# repeat visits, and existing opinion has some momentum.
delta = (
    2.0
    + friendliness * colorMatch * 6.0
    - aggression * (1.2 - patience) * 5.0
    + curiosity * np.minimum(timesTalked, 5) * 0.3
    + (opinion / 100.0) * 1.5
)
delta = np.clip(delta, -10, 10)
punch = sigmoid(-(opinion + 50) / 15.0 - patience * 3 + aggression * 2)

X = np.column_stack([curiosity, friendliness, patience, opinion / 100.0, timesTalked / 20.0, colorMatch, aggression, dayNight])
Y = np.column_stack([delta / 10.0, punch])   # keep targets in a small range; the C++ side un-scales opinionDelta by *10

model = MLPRegressor(hidden_layer_sizes=(8,), activation="tanh", max_iter=4000, random_state=0)
model.fit(X, Y)

W1, W2 = model.coefs_
B1, B2 = model.intercepts_

def emit(name, arr):
    if arr.ndim == 1:
        vals = ", ".join(f"{v:.6f}f" for v in arr)
        return f"const float {name}[{len(arr)}] = {{{vals}}};"
    rows = ["{" + ", ".join(f"{v:.6f}f" for v in row) + "}" for row in arr]
    return f"const float {name}[{arr.shape[0]}][{arr.shape[1]}] = {{{', '.join(rows)}}};"

with open("npc_brain_weights.h", "w") as f:
    f.write("// AUTO-GENERATED by train_brain.py - do not edit by hand. Re-run the script to regenerate.\n")
    f.write("#pragma once\n")
    f.write("const int HIDDEN_SIZE = 8;\n")
    f.write(emit("W1", W1) + "\n")
    f.write(emit("B1", B1) + "\n")
    f.write(emit("W2", W2) + "\n")
    f.write(emit("B2", B2) + "\n")

print("Wrote npc_brain_weights.h")
print("sanity check - friendly NPC, player wearing their favorite color:")
print("  ", model.predict([[0.8, 0.9, 0.5, 0, 2/20, 1, 0, 0.5]]) * [10, 1])
print("sanity check - impatient NPC, player wearing a disliked color and acting hostile:")
print("  ", model.predict([[0.3, 0.3, 0.1, -60/100, 10/20, -1, 1, 0.5]]) * [10, 1])